<?php

module_load_include('inc', 'bibdk_furthersearch', 'bibdk_furthersearch.field');

/**
 * Implements hook_menu().
 */
function bibdk_furthersearch_menu() {
  //XXX mmj is this method necessary?
  $items['bibdk_furthersearch/submit'] = array(
    'page callback' => 'bibdk_furthersearch_form_submit',
    'page arguments' => array(1, 2, 3, 4, 5, 6),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function bibdk_furthersearch_theme() {
  //XXX mmj is this method necessary?
  return array(
    'bibdk_furthersearch_tab_content' => array(
      'variables' => array('types' => array(), 'fictions' => array(), 'elements' => array()),
      'template' => 'theme/bibdk_furthersearch',
    )
  );
}

/**
 * Returns table with checkboxes for further searches
 *
 * @param array $furtherSearchArray
 * @param string $id
 * @return array
 */
function bibdk_furthersearch_get_table($furtherSearchArray, $id) {
  $header = array(
    t('further_search_types', array(), array('context' => 'bibdk_furthersearch')),
    t('further_search_elements', array(), array('context' => 'bibdk_furthersearch')),
    t('further_search_fictions', array(), array('context' => 'bibdk_furthersearch')),
  );

  $rows = _bibdk_furthersearch_get_rows($furtherSearchArray);
  $uid = _bibdk_furthersearch_trim_string($id);

  $table['table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => t('no_further_search_found', array(), array('context' => 'bibdk_furthersearch')),
    '#attributes' => array(
      'class' => array(
        'further-search-table-' . $uid,
      ),
    ),
  );

  $table['submit'] = array(
    '#theme' => 'button',
    '#value' => t('do_search', array(), array('context' => 'bibdk_furthersearch')),
    '#attributes' => array(
      'class' => array(
        'further-search-btn',
      ),
      'data-id' => array(
        $uid,
      ),
    ),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'bibdk_furthersearch') . '/js/bibdk_furthersearch.js'
      ),
    ),
  );

  return $table;
}

/**
 * Produces rows for the further search table displayed on manifestation level
 *
 * @param $furtherSearchArray
 * @return array
 */
function _bibdk_furthersearch_get_rows($furtherSearchArray) {
  $rows = array();

  $types = array_values($furtherSearchArray['types']);
  $elements = array_values($furtherSearchArray['elements']);
  $fictions = array_values($furtherSearchArray['fictions']);

  $length = max(count($types), count($elements), count($fictions));

  for ($i = 0; $i < $length; $i++) {
    $type = isset($types[$i]) ? _bibdk_furthersearch_create_checkbox($types[$i], 'type') : '';
    $element = isset($elements[$i]) ? _bibdk_furthersearch_create_checkbox($elements[$i], 'element') : '';
    $fiction = isset($fictions[$i]) ? _bibdk_furthersearch_create_checkbox($fictions[$i], 'fiction') : '';
    $rows[] = array($type, $element, $fiction);
  }
  return $rows;
}

/**
 * Returns one single checkbox representing a further search parameter
 *
 * @param array $element The element
 * @param string $type
 * @return string HTML for a checkbox
 */
function _bibdk_furthersearch_create_checkbox($element, $type) {

  $checkbox = array(
    '#theme' => 'checkbox',
    '#attributes' => array(
      'class' => array(
        'further-search-checkbox',
      ),
      'data-code' => array(
        $element['searchCode'],
      ),
      'data-type' => array(
        $type
      ),
    ),
  );

  $output = drupal_render($checkbox);
  $output .= $element['display'];

  return $output;
}

/**
 * Strips a string (pid) for :, -, __
 *
 * @param string $string
 * @return string
 */
function _bibdk_furthersearch_trim_string($string) {
  return strtolower(strtr($string, array(':' => '', '-' => '', '__' => '')));
}
